// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeaBattleASP.Helpers;

namespace SeaBattleASP.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeaBattleASP.Models.AuxiliaryShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSelectedShip");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("Range");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("AuxiliaryShips");
                });

            modelBuilder.Entity("SeaBattleASP.Models.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color");

                    b.Property<int>("State");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("SeaBattleASP.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsHead");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("SeaBattleASP.Models.DeckCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuxiliaryShipId");

                    b.Property<int?>("CellId");

                    b.Property<int?>("DeckId");

                    b.Property<int?>("MilitaryShipId");

                    b.Property<int?>("MixShipId");

                    b.Property<int?>("PlayingFieldId");

                    b.HasKey("Id");

                    b.HasIndex("AuxiliaryShipId");

                    b.HasIndex("CellId");

                    b.HasIndex("DeckId");

                    b.HasIndex("MilitaryShipId");

                    b.HasIndex("MixShipId");

                    b.HasIndex("PlayingFieldId");

                    b.ToTable("DeckCells");
                });

            modelBuilder.Entity("SeaBattleASP.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPl1Turn");

                    b.Property<int?>("Player1Id");

                    b.Property<int?>("Player2Id");

                    b.Property<int?>("PlayingFieldId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("PlayingFieldId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SeaBattleASP.Models.MilitaryShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSelectedShip");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("Range");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("MilitaryShips");
                });

            modelBuilder.Entity("SeaBattleASP.Models.MixShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSelectedShip");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("Range");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("MixShips");
                });

            modelBuilder.Entity("SeaBattleASP.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SeaBattleASP.Models.PlayingField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Heigth");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("PlayingField");
                });

            modelBuilder.Entity("SeaBattleASP.Models.AuxiliaryShip", b =>
                {
                    b.HasOne("SeaBattleASP.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("SeaBattleASP.Models.DeckCell", b =>
                {
                    b.HasOne("SeaBattleASP.Models.AuxiliaryShip")
                        .WithMany("Decks")
                        .HasForeignKey("AuxiliaryShipId");

                    b.HasOne("SeaBattleASP.Models.Cell", "Cell")
                        .WithMany()
                        .HasForeignKey("CellId");

                    b.HasOne("SeaBattleASP.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId");

                    b.HasOne("SeaBattleASP.Models.MilitaryShip")
                        .WithMany("Decks")
                        .HasForeignKey("MilitaryShipId");

                    b.HasOne("SeaBattleASP.Models.MixShip")
                        .WithMany("Decks")
                        .HasForeignKey("MixShipId");

                    b.HasOne("SeaBattleASP.Models.PlayingField")
                        .WithMany("ShipsDeckCells")
                        .HasForeignKey("PlayingFieldId");
                });

            modelBuilder.Entity("SeaBattleASP.Models.Game", b =>
                {
                    b.HasOne("SeaBattleASP.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id");

                    b.HasOne("SeaBattleASP.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");

                    b.HasOne("SeaBattleASP.Models.PlayingField", "PlayingField")
                        .WithMany()
                        .HasForeignKey("PlayingFieldId");
                });

            modelBuilder.Entity("SeaBattleASP.Models.MilitaryShip", b =>
                {
                    b.HasOne("SeaBattleASP.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("SeaBattleASP.Models.MixShip", b =>
                {
                    b.HasOne("SeaBattleASP.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
